version: "3"
services:
  php:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - "./api:/app"
    ports:
      - "${PHP_PORT}:8000"
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
    ports:
      - "${NGINX_PORT}:80"
  mysql:
    image: "mysql:8.3"
    volumes:
      - "./mysql/var/log/mysql:/var/lib/mysql:delegated"
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tastingNote
      MYSQL_USER: tastingNote
      MYSQL_PASSWORD: tastingNote