version: "3"
services:
  front:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    volumes:
      - "./front:/app"
    ports:
      - "${FRONT_PORT}:3000"
  php:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - "./api:/app"
      - "./api/php.ini:/usr/local/etc/php/php.ini"
    ports:
      - "${PHP_PORT}:8000"
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "${NGINX_PORT}:80"
  mysql:
    image: "mysql:8.3"
    volumes:
      - "./mysql/var/log/mysql:/var/lib/mysql:delegated"
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tastingNote
      MYSQL_USER: tastingNote
      MYSQL_PASSWORD: tastingNote
  minio:
      image: minio/minio:RELEASE.2025-01-20T14-49-07Z-cpuv1
      volumes:
        - "./minio/data:/minio/data" # 任意の設定
      ports:
        - "${MINIO_API_PORT}:9000"
        - "${MINIO_PORT}:9001"
      environment:
        MINIO_ROOT_USER: "minio_root"
        MINIO_ROOT_PASSWORD: "minio_password"
      command: server --console-address ":9001" /minio/data