version: "3"
services:
  php:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - "./api:/app"
    ports:
      - "${PHP_PORT}:8000"
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
    ports:
      - "${NGINX_PORT}:80"
  mysql:
    image: mysql:8.4
    ports:
      - "${MYSQL_PORT}:3306"